### ISSUE TITLE
Unexpected keyword_end when run "rails generate noticent:install"

### ISSUE THREAD

**Issue by zarulrahim** [cloud66-oss/noticent#11]
Sorry for open this issue, but i keep getting this following error while running "rails generate noticent:install" command. 

Below is a line that might helps describe the issue a lil bit details,

.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/noticent-0.0.3/lib/noticent/definitions/channel.rb:48: syntax error, unexpected keyword_end, expecting end-of-input (SyntaxError)

**Comment by khash** [comment]
@zarulizham97 I can't reproduce this on 0.0.3 and the mentioned file looks fine from the syntax point of view which would also fail the tests which are passing. 
Could this be a configuration issue or something else perhaps?
