### ISSUE TITLE
Not compatible with Rails API only apps

### ISSUE THREAD

**Issue by dkrusenstrahle** [cloud66-oss/noticent#18]
Hello,

I am running a Rails 5.2 (api mode) app.
I try to run the installation but I get the below error:

<class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Is it possible to use this gem with a Rails app that is API only?

**Comment by khash** [comment]
This looks like an issue caused by Sprocket update to 4.0 and not Rails itself. The new version of the gem (0.0.5) works with Sprockets 4.0 and therefore should be ok.
