### ISSUE TITLE
payload Noticent::AccountPayload doesn't have a class method called new_signup (Noticent::BadConfiguration)

### ISSUE THREAD

**Issue by Anandshr** [cloud66-oss/noticent#21]
The gem is not configuring as per its documentation 

payload Noticent::AccountPayload doesn't have a class method called new_signup (Noticent::BadConfiguration)

**Comment by khash** [comment]
This sounds like a app specific configuration issue. Can you put the config file you are using here please?

**Comment by Anandshr** [comment]
I have done everything as per the doc but getting some of the errors after like :

- _payload class Noticent::AccountPayload does have an attribute or method called account_id (Noticent::BadConfiguration_

- account_payload = AccountPayload.new(1, user.first) uninitialized constant AccountPayload

- _(wrong number of arguments (given 2, expected 0)) when I am calling account_payload = Noticent::AccountPayload.new(1, User.first)

- _Noticent::BadConfiguration (payload (Noticent::AccountPayload) doesn't belong to this scope (account) as it requires Noticent::AccountPayload)

    Noticent.configure do |config|
    config.base_dir = File.join(Rails.root, 'app', 'models', 'noticent')
    config.base_module_name = 'Noticent'
    config.logger = Rails.logger
    config.halt_on_error = !Rails.env.production?
    config.use_sub_modules = false

    channel :email

    scope :account do
        alert(:new_signup) { notify :owner}
    end

    end
    
also in the doc mention class Email < ::Noticent::Channel but the scope is also needed class Noticent::Email < ::Noticent::Channel same for payload class Noticent::AccountPayload instead of class AccountPayload 
    
I request also please update the doc..
